#!/usr/bin/env python3
"""Exact bounded future-compatibility probe for the physical tagged tokens.

This program joins four pinned finite artifacts into the one correlated tree
that they actually describe::

    42 realized L7 parent corridors
       -> 146 realized L8 child corridors
          -> 488 initial-anchor L9 precursor corridors.

It is deliberately *not* an all-point-pair experiment.  The only deep
objects are the two physical source tokens already audited by
``deep_incidence_lineage.py``: one ordered pair of stable L7 endpoint
identities and one singleton stable L7 endpoint identity.  Their endpoints
are never split into independent address streams.  Every state retains the
actual selected L7/L8 connector word, its parent/slot address, and the
ordered tuple of successors generated by that one selected word.

For L8 the upstream deep artifact retained atom descriptions and exact mask
commitments but omitted raw bitsets.  ``run`` therefore rescans only the 151
requested (step, atom) objects over 40 connector domains.  It does not rescan
placed-point pairs.  The reconstructed raw bitsets are checked against every
upstream atom and aggregate channel commitment before they are used.

For L9 the precursor already contains reconstructible raw bitsets.  They are
decoded and checked before use.  The resulting local compatibility signature
has three overlapping components:

* direct: a candidate site on the carried tagged--tagged secant;
* endpoint: tagged-endpoint collision or a tagged endpoint on a
  candidate-internal line; and
* near-deep: a candidate site on a tagged-endpoint--placed-partner secant.

Near-deep masks are ORed exactly by partner birth age and by the base-three
shell of the exact joint owner radius.  L8 owner spans are the prefix-aware
pipeline spans stored by the deep audit.  L9 owner spans are reconstructed
from the exact completed-L8 block address and the initial-anchor owner tiles.
All ORs used by partition refinement are performed on raw integers, never on
mask hashes.  Hashes in the output are commitments to emitted compressed raw
payloads, not a substitute for semantic mask operations.

Bottom-up partition refinement is reported for channel-only,
birth/owner-shell, physical-partner, and literal-address keys.  A repeated
key with two distinct ordered successor colors is a finite falsifier of that
key on this tree.  Lack of such a disagreement is only non-falsification.

Critical omissions remain:

* there is no selected L9 connector word and no current-L9 connector prefix;
* L9 near-deep joins contain all 311,738 initial anchors but no current-L9
  connector interiors;
* only one recorded connector history is present; and
* no alternate-action Post closure, availability bound, contraction, or
  infinite safety certificate is attempted.

Run from the repository root on one low-priority thread::

    env OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 \
        VECLIB_MAXIMUM_THREADS=1 NUMEXPR_NUM_THREADS=1 \
        nice -n 15 python3 -B \
        design/far_secant_future_compatibility_probe.py estimate

    env OPENBLAS_NUM_THREADS=1 OMP_NUM_THREADS=1 MKL_NUM_THREADS=1 \
        VECLIB_MAXIMUM_THREADS=1 NUMEXPR_NUM_THREADS=1 \
        nice -n 15 python3 -B \
        design/far_secant_future_compatibility_probe.py run \
        --output /tmp/far-secant-future-compatibility-probe.json
"""

from __future__ import annotations

import argparse
import base64
import bisect
import hashlib
import json
import math
import os
import pickle
import re
import sys
import tempfile
import time
import zlib
from collections import Counter, defaultdict
from itertools import product
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]

DEFAULT_FUTURE = Path("/tmp/far-secant-future-trace-canonical.json")
DEFAULT_BIRTH = Path("/tmp/far-secant-birth-shell-trace-canonical.json")
DEFAULT_DEEP = Path("/tmp/deep-incidence-lineage-final-canonical.json")
DEFAULT_L9 = Path("/tmp/l9-anchor-age2-precursor-canonical.json")

EXPECTED_INPUT_SHA256 = {
    "future": "611bf74be1d42bd15d311964603daa573f8ff39a0f3bcb9542f4063341919b87",
    "birth": "5c525ef4cc0c77ed96a2f67238e785d0382ead806f96479854a691498de99488",
    "deep": "7195c4d72a71c0b819da1c2d9ba16165ea2aa1c71ffdfd61ae980fc7975388ab",
    "l9": "961f9e5f0772d9df508ab0aefaa7405e3cc21637d59560cdda95c4edf61d809f",
    "viz/walk3d-data.json": "d4392af018ee7d7c40c224622e9a606d3b1fb3da0c8c25613c93cb2dc901c883",
    "gate2-l7-construction-L8.pkl": "cc4002ebccde737ab46dc016937be4aa653620d809908d48d35bcf06fc884141",
    "connector_domains4.pkl": "d3dbfd54b724b91b1391d2233931a865a5ff371789029556949c953419fa3e4f",
    "dstar5_fragile.pkl": "fe6ca45eda2874833d8257324bf7e29e2a4e855b0c4c27a9d2312702f28aefb3",
}

EXPECTED_CHECKER_SHA256 = {
    "future": "6f286cb118166c1375eb777ec6e24bcdc58766b98538099c604eb97b5c3dd430",
    "birth": "dd35f8ac5459d6df05d8b960f82b709f69380268ed144ac5c0e6789d178c35b9",
    "deep": "cde329fafc79ec95ea0f3d8d8a060219af45633f6414f7f3fb8426fad4888be7",
    "l9": "66f776e7ae4eff4c35d004d870d82458582a4c2b6516f20257149a08e5535b90",
}

THREAD_ENV_VARS = (
    "OPENBLAS_NUM_THREADS",
    "OMP_NUM_THREADS",
    "MKL_NUM_THREADS",
    "VECLIB_MAXIMUM_THREADS",
    "NUMEXPR_NUM_THREADS",
)

FRAGILE_CUT = 2_000
EXPECTED_TREE = {"l7": 42, "l8": 146, "l9": 488}
EXPECTED_L8_RESCAN = {
    "effect_records": 64,
    "requested_atom_occurrences": 156,
    "unique_step_atoms": 151,
    "effective_steps": 40,
    "domain_words": 3_751_509,
}

CHANNELS_L8 = (
    "collision",
    "endpoint-old-new-new",
    "tagged-tagged-old-old",
    "tagged-other-old-old",
)
CHANNELS_L9 = (
    "collision",
    "endpoint-old-new-new",
    "tagged-tagged-old-old",
    "tagged-other-anchor-old-old",
)

SOURCE_DEFINITIONS = {
    13171: {
        "witness_type": "old-old-secant",
        "tagged_endpoint_stable_ids": (
            "connector:L7:G12291:I1",
            "connector:L7:G12324:I2",
        ),
    },
    21115: {
        "witness_type": "old-new-new-line",
        "tagged_endpoint_stable_ids": (
            "connector:L7:G19950:I2",
        ),
    },
}

STABLE_CONNECTOR_RE = re.compile(
    r"^connector:L(?P<level>[0-9]+):G(?P<gap>[0-9]+):I(?P<ordinal>[0-9]+)$"
)


def file_sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def as_json(value):
    if isinstance(value, tuple):
        return [as_json(item) for item in value]
    if isinstance(value, list):
        return [as_json(item) for item in value]
    if isinstance(value, dict):
        return {str(key): as_json(item) for key, item in value.items()}
    return value


def stable_bytes(value):
    return json.dumps(
        as_json(value), sort_keys=True, separators=(",", ":")
    ).encode("utf-8")


def stable_hash(value):
    return hashlib.sha256(stable_bytes(value)).hexdigest()


def mask_raw(bits, size):
    return bits.to_bytes((size + 7) // 8, "little")


def mask_sha256(bits, size):
    return hashlib.sha256(mask_raw(bits, size)).hexdigest()


def normalize(value):
    if isinstance(value, dict):
        return tuple(
            (normalize(key), normalize(item))
            for key, item in sorted(value.items(), key=lambda pair: str(pair[0]))
        )
    if isinstance(value, list):
        return tuple(normalize(item) for item in value)
    if isinstance(value, tuple):
        return tuple(normalize(item) for item in value)
    return value


def parse_stable_connector(stable_id):
    match = STABLE_CONNECTOR_RE.match(stable_id)
    if match is None:
        raise ValueError(f"not a connector stable id: {stable_id}")
    return {
        key: int(value) for key, value in match.groupdict().items()
    }


def base3_shell(distance):
    """0 for zero; j>=1 is least j with distance <= 3**(j-1)."""
    if distance < 0:
        raise ValueError("negative owner distance")
    if distance == 0:
        return 0
    shell = 1
    ceiling = 1
    while distance > ceiling:
        shell += 1
        ceiling *= 3
    return shell


def pareto_spans(owner_options, target_tile):
    """Exact nondominated signed (left,right) spans over joint owners."""
    spans = {(0, 0)}
    for options in owner_options:
        nxt = set()
        for left, right in spans:
            for owner in options:
                nxt.add((
                    max(left, target_tile - owner, 0),
                    max(right, owner - target_tile, 0),
                ))
        spans = {
            pair for pair in nxt
            if not any(
                other != pair
                and other[0] <= pair[0]
                and other[1] <= pair[1]
                for other in nxt
            )
        }
    return tuple(sorted(spans))


def owner_profile(owner_options, target_tile):
    owner_options = tuple(tuple(options) for options in owner_options)
    spans = pareto_spans(owner_options, target_tile)
    radius = min(max(span) for span in spans)
    return {
        "owner_options": as_json(owner_options),
        "target_tile": target_tile,
        "owner_pareto_spans": as_json(spans),
        "minimum_joint_owner_radius": radius,
        "minimum_joint_owner_base3_shell": base3_shell(radius),
    }


def enforce_resource_policy():
    observed = {name: os.environ.get(name) for name in THREAD_ENV_VARS}
    if any(value != "1" for value in observed.values()):
        raise RuntimeError(
            "set every BLAS/OpenMP thread environment variable to 1: "
            + json.dumps(observed, sort_keys=True)
        )
    nice = os.nice(0)
    if nice < 15:
        raise RuntimeError(f"run under nice -n 15 or lower priority; got {nice}")
    return {"processes": 1, "thread_cap": 1, "nice": nice}


class ExactMaskStore:
    """Deduplicated, reconstructible exact bitset payloads."""

    def __init__(self):
        self.payloads = {}

    def record(self, bits, domain_words):
        raw = mask_raw(bits, domain_words)
        digest = hashlib.sha256(raw).hexdigest()
        reference = f"{domain_words}:{digest}"
        if reference not in self.payloads:
            compressed = zlib.compress(raw, level=9)
            self.payloads[reference] = {
                "domain_words": domain_words,
                "uncompressed_bytes": len(raw),
                "zlib_bytes": len(compressed),
                "encoding": (
                    "zlib+base64 fixed-length little-endian word bitset; "
                    "bit i is domain word i"
                ),
                "payload_base64": base64.b64encode(compressed).decode("ascii"),
            }
        return {
            "domain_words": domain_words,
            "killed_words": bits.bit_count(),
            "mask_sha256": digest,
            "exact_payload_ref": reference,
        }


def decode_input_mask(record, payloads):
    reference = record["exact_payload_ref"]
    payload = payloads[reference]
    assert payload["domain_words"] == record["domain_words"]
    raw = zlib.decompress(base64.b64decode(payload["payload_base64"]))
    assert len(raw) == payload["uncompressed_bytes"]
    assert hashlib.sha256(raw).hexdigest() == record["mask_sha256"]
    bits = int.from_bytes(raw, "little")
    assert bits.bit_count() == record["killed_words"]
    assert bits >> record["domain_words"] == 0
    return bits


def load_json(path):
    with path.open() as handle:
        return json.load(handle)


def validate_inputs(args):
    paths = {
        "future": args.future,
        "birth": args.birth,
        "deep": args.deep,
        "l9": args.l9,
    }
    observed = {}
    data = {}
    for name, path in paths.items():
        observed[name] = file_sha256(path)
        if observed[name] != EXPECTED_INPUT_SHA256[name]:
            raise RuntimeError(
                f"pinned {name} artifact hash mismatch: {observed[name]}"
            )
        data[name] = load_json(path)
        if data[name]["checker_sha256"] != EXPECTED_CHECKER_SHA256[name]:
            raise RuntimeError(f"pinned {name} checker hash mismatch")

    for relative in (
        "viz/walk3d-data.json",
        "gate2-l7-construction-L8.pkl",
        "connector_domains4.pkl",
        "dstar5_fragile.pkl",
    ):
        observed[relative] = file_sha256(ROOT / relative)
        assert observed[relative] == EXPECTED_INPUT_SHA256[relative]

    future = data["future"]
    birth = data["birth"]
    deep = data["deep"]
    l9 = data["l9"]
    assert len(future["parent_states"]) == EXPECTED_TREE["l7"]
    assert len(future["child_states"]) == EXPECTED_TREE["l8"]
    assert len(birth["parent_states"]) == EXPECTED_TREE["l7"]
    assert len(birth["child_states"]) == EXPECTED_TREE["l8"]
    assert len(l9["exact_corridor_masks"]["records"]) == EXPECTED_TREE["l9"]
    assert l9["upstream_trace"]["sha256"] == observed["birth"]
    assert birth["deep_result_sha256"] == observed["deep"]
    assert future["deep_result"]["sha256"] == observed["deep"]
    return data, observed


def add(left, right):
    return tuple(left[axis] + right[axis] for axis in range(3))


def sub(left, right):
    return tuple(left[axis] - right[axis] for axis in range(3))


def cross(left, right):
    return (
        left[1] * right[2] - left[2] * right[1],
        left[2] * right[0] - left[0] * right[2],
        left[0] * right[1] - left[1] * right[0],
    )


def primitive(vector):
    divisor = 0
    for value in vector:
        divisor = math.gcd(divisor, abs(value))
    if divisor == 0:
        return None
    result = tuple(value // divisor for value in vector)
    for value in result:
        if value:
            return tuple(-item for item in result) if value < 0 else result
    raise AssertionError("unreachable zero primitive")


def line_key(first, second):
    direction = primitive(sub(second, first))
    if direction is None:
        return None
    return direction, cross(first, direction)


def word_offsets(word, menu):
    position = (0, 0, 0)
    offsets = []
    for ordinal, menu_index in enumerate(word):
        position = add(position, menu[menu_index])
        if ordinal + 1 < len(word):
            offsets.append(position)
    return offsets


def deep_occurrences(deep):
    records = []
    for source in deep["all_domain_endpoint_incidence_closure"]["per_source"]:
        for record in source["occurrences"]:
            assert record["source_gap"] == source["source_gap"]
            records.append(record)
    records.sort(key=lambda record: (record["source_gap"], record["l8_gap"]))
    return records


def requested_atom_inventory(deep):
    occurrences = deep_occurrences(deep)
    requested = defaultdict(dict)
    atom_occurrences = 0
    for record in occurrences:
        step = record["l8_step"]
        for atom in record["atoms"]:
            atom_occurrences += 1
            key = normalize(atom["atom_description"])
            previous = requested[step].get(key)
            commitment = atom["word_membership"]
            if previous is not None:
                assert previous == commitment
            requested[step][key] = commitment
    model_sizes = {
        record["step"]: record["domain_words"]
        for record in deep["all_domain_endpoint_incidence_closure"][
            "model_census"
        ]
    }
    census = {
        "effect_records": len(occurrences),
        "requested_atom_occurrences": atom_occurrences,
        "unique_step_atoms": sum(len(atoms) for atoms in requested.values()),
        "effective_steps": len(requested),
        "domain_words": sum(model_sizes[step] for step in requested),
    }
    assert census == EXPECTED_L8_RESCAN
    return requested, model_sizes, census


def rescan_l8_atom_masks(deep):
    requested, model_sizes, census = requested_atom_inventory(deep)
    result_buffers = {}
    target_indexes = {}
    for step in requested:
        site_targets = {
            atom[1]: atom for atom in requested[step]
            if atom[0] == "site"
        }
        line_targets = {
            atom[1]: atom for atom in requested[step]
            if atom[0] == "line"
        }
        assert len(site_targets) + len(line_targets) == len(requested[step])
        byte_count = (model_sizes[step] + 7) // 8
        result_buffers[step] = {
            atom: bytearray(byte_count) for atom in requested[step]
        }
        target_indexes[step] = (site_targets, line_targets)

    def scan_words(step, words, start_index, menu):
        site_targets, line_targets = target_indexes[step]
        buffers = result_buffers[step]
        for local_index, word in enumerate(words):
            word_index = start_index + local_index
            offsets = word_offsets(word, menu)
            if site_targets:
                for offset in set(offsets):
                    atom = site_targets.get(offset)
                    if atom is not None:
                        buffers[atom][word_index >> 3] |= 1 << (
                            word_index & 7
                        )
            if line_targets:
                lines = set()
                for left, first in enumerate(offsets):
                    for second in offsets[left + 1:]:
                        key = line_key(first, second)
                        if key is not None:
                            lines.add(key)
                for key in lines:
                    atom = line_targets.get(key)
                    if atom is not None:
                        buffers[atom][word_index >> 3] |= 1 << (
                            word_index & 7
                        )

    # Scan base domains while the base pickle is resident, then release it
    # before opening the much larger fragile extension.  This avoids holding
    # the two full pickle object graphs simultaneously.
    with (ROOT / "connector_domains4.pkl").open("rb") as handle:
        base = pickle.load(handle)
    menu = tuple(map(tuple, base["menu"]))
    index = {vector: ordinal for ordinal, vector in enumerate(menu)}
    base_sizes = {}
    for step in sorted(requested):
        words = sorted(base["domains"][step], key=len)
        base_sizes[step] = len(words)
        scan_words(step, words, 0, menu)
        del words
    del base

    fragile_counts = Counter()
    with (ROOT / "dstar5_fragile.pkl").open("rb") as handle:
        fragile = pickle.load(handle)
    for vector, words in fragile.items():
        step = index[tuple(vector)]
        if step not in requested:
            continue
        assert base_sizes[step] < FRAGILE_CUT
        indexed_words = (
            tuple(index[tuple(menu_step)] for menu_step in word)
            for word in words
        )
        scan_words(step, indexed_words, base_sizes[step], menu)
        fragile_counts[step] = len(words)
    del fragile

    result = {}
    per_step = []
    for step in sorted(requested):
        domain_words = base_sizes[step] + fragile_counts[step]
        assert domain_words == model_sizes[step]
        site_targets, line_targets = target_indexes[step]
        buffers = result_buffers.pop(step)
        for atom, buffer in buffers.items():
            bits = int.from_bytes(buffer, "little")
            commitment = requested[step][atom]
            assert bits.bit_count() == commitment["words"]
            assert mask_sha256(bits, domain_words) == commitment["mask_sha256"]
            result[(step, atom)] = bits
        per_step.append({
            "step": step,
            "base_domain_words": base_sizes[step],
            "fragile_extension_words": fragile_counts[step],
            "domain_words": domain_words,
            "requested_site_atoms": len(site_targets),
            "requested_line_atoms": len(line_targets),
        })
    assert not result_buffers
    return result, per_step, census


def mask_key(bits_by_shell):
    return tuple(sorted((normalize(key), bits) for key, bits in bits_by_shell.items()))


def output_mask_map(bits_by_key, domain_words, store):
    return [
        {
            "key": as_json(key),
            "mask": store.record(bits, domain_words),
        }
        for key, bits in sorted(bits_by_key.items())
    ]


def source_endpoint_origins(l9):
    profiles = l9["anchor_skeleton"]["tagged_endpoint_profiles"]
    result = {profile["stable_id"]: profile for profile in profiles}
    expected = {
        stable_id
        for definition in SOURCE_DEFINITIONS.values()
        for stable_id in definition["tagged_endpoint_stable_ids"]
    }
    assert set(result) == expected
    return result


def l8_source_owner_profiles(source_gap, target_tile, endpoint_origins):
    definition = SOURCE_DEFINITIONS[source_gap]
    endpoints = []
    owner_options = []
    for stable_id in definition["tagged_endpoint_stable_ids"]:
        parsed = parse_stable_connector(stable_id)
        assert parsed["level"] == 7
        profile = endpoint_origins[stable_id]
        assert profile["birth_gap"] == parsed["gap"]
        options = (parsed["gap"],)
        owner_options.append(options)
        endpoints.append({
            "stable_id": stable_id,
            "birth_level": 7,
            "birth_age_at_observation": 1,
            "birth_gap": parsed["gap"],
            "interior_ordinal": parsed["ordinal"],
            "birth_parent_endpoint_stable_ids": profile[
                "birth_parent_endpoint_stable_ids"
            ],
            **owner_profile((options,), target_tile),
        })
    joint = owner_profile(owner_options, target_tile)
    return endpoints, joint


def validate_commitment(bits, domain_words, commitment):
    assert bits.bit_count() == commitment["words"]
    assert mask_sha256(bits, domain_words) == commitment["mask_sha256"]


def build_l8_states(
    future, birth, deep, l9, raw_atom_masks, store,
):
    endpoint_origins = source_endpoint_origins(l9)
    occurrences = {
        (record["source_gap"], record["l8_gap"]): record
        for record in deep_occurrences(deep)
    }
    assert len(occurrences) == EXPECTED_L8_RESCAN["effect_records"]
    birth_children = {
        (record["source_gap"], record["l8_gap"]): record
        for record in birth["child_states"]
    }
    future_parents = {
        (record["source_gap"], record["l7_parent_gap"]): record
        for record in future["parent_states"]
    }

    states = []
    raw = {}
    for child in sorted(
        future["child_states"],
        key=lambda record: (record["source_gap"], record["l8_gap"]),
    ):
        source_gap = child["source_gap"]
        definition = SOURCE_DEFINITIONS[source_gap]
        assert child["centered_geometry"]["witness_type"] == definition[
            "witness_type"
        ]
        identity = (source_gap, child["l7_parent_gap"], child["l8_gap"])
        observation = child["observation"]
        domain_words = observation["domain_size"]
        channel_bits = {channel: 0 for channel in CHANNELS_L8}
        endpoint_component_bits = {
            stable_id: 0 for stable_id in definition[
                "tagged_endpoint_stable_ids"
            ]
        }
        partner_bits = defaultdict(int)
        near_shell_bits = defaultdict(int)
        near_terms = []
        occurrence = occurrences.get((source_gap, child["l8_gap"]))
        if occurrence is not None:
            assert occurrence["domain_size"] == domain_words
            assert occurrence["l8_step"] == child["step"]
            assert occurrence["address"]["l7_parent_gap"] == child[
                "l7_parent_gap"
            ]
            assert occurrence["address"][
                "actual_connector_step_slot_zero_based"
            ] == child["actual_parent_connector_step_slot_zero_based"]
            assert occurrence["address"]["actual_connector_word"] == (
                future_parents[(source_gap, child["l7_parent_gap"])][
                    "actual_selected_connector_word"
                ]
            )
            target_tile = occurrence["pipeline_tile"]
            assert target_tile == child["l7_parent_gap"]
            for atom in occurrence["atoms"]:
                atom_key = normalize(atom["atom_description"])
                bits = raw_atom_masks[(child["step"], atom_key)]
                validate_commitment(bits, domain_words, atom["word_membership"])
                for witness in atom["witnesses"]:
                    channel = witness["channel"]
                    channel_bits[channel] |= bits
                    tagged_id = witness["tagged_endpoint"]["stable_id"]
                    if channel in ("collision", "endpoint-old-new-new"):
                        endpoint_component_bits[tagged_id] |= bits
                    partner = witness.get("partner")
                    if channel == "tagged-other-old-old":
                        assert partner is not None
                        partner_id = partner["stable_id"]
                        partner_bits[partner_id] |= bits
                        tagged = witness["tagged_endpoint"]
                        joint_owner = owner_profile(
                            (
                                tuple(tagged["owner_options"]),
                                tuple(partner["owner_options"]),
                            ),
                            target_tile,
                        )
                        assert joint_owner["owner_pareto_spans"] == witness[
                            "owner_pareto_spans"
                        ]
                        assert joint_owner[
                            "minimum_joint_owner_radius"
                        ] == witness["minimum_owner_radius"]
                        shell_key = (
                            tagged["age"],
                            partner["age"],
                            joint_owner[
                                "minimum_joint_owner_base3_shell"
                            ],
                        )
                        near_shell_bits[shell_key] |= bits
                        near_terms.append({
                            "atom": atom["atom_description"],
                            "mask": store.record(bits, domain_words),
                            "tagged_endpoint_stable_id": tagged_id,
                            "tagged_birth_level": tagged["birth_level"],
                            "tagged_birth_age": tagged["age"],
                            "tagged_owner_options": tagged["owner_options"],
                            "partner_stable_id": partner_id,
                            "partner_birth_level": partner["birth_level"],
                            "partner_birth_age": partner["age"],
                            "partner_owner_options": partner["owner_options"],
                            "joint_owner": joint_owner,
                        })
            for channel in CHANNELS_L8:
                validate_commitment(
                    channel_bits[channel], domain_words,
                    occurrence["primary_channel_membership_masks_overlap"][
                        channel
                    ],
                )
            full = 0
            for bits in channel_bits.values():
                full |= bits
            validate_commitment(
                full, domain_words, occurrence["endpoint_closure"]
            )
            assert (
                (full >> occurrence["chosen_word_index"]) & 1
            ) == 0
        else:
            target_tile = child["l7_parent_gap"]
            full = 0
            assert not child["observation"]["deep_record_effectful"]

        validate_commitment(
            full, domain_words, observation["endpoint_closure"]
        )
        birth_child = birth_children[(source_gap, child["l8_gap"])]
        assert birth_child["deep_record_effectful"] == bool(full)
        validate_commitment(
            full, domain_words,
            birth_child["decomposition"]["full_killed_word_mask"],
        )

        direct = channel_bits["tagged-tagged-old-old"]
        endpoint = (
            channel_bits["collision"]
            | channel_bits["endpoint-old-new-new"]
        )
        near = channel_bits["tagged-other-old-old"]
        assert full == direct | endpoint | near
        source_endpoints, joint_source_owner = l8_source_owner_profiles(
            source_gap, target_tile, endpoint_origins
        )
        endpoint_shell_bits = defaultdict(int)
        for profile in source_endpoints:
            key = (
                profile["birth_age_at_observation"],
                profile["minimum_joint_owner_base3_shell"],
            )
            endpoint_shell_bits[key] |= endpoint_component_bits[
                profile["stable_id"]
            ]

        parent = future_parents[(source_gap, child["l7_parent_gap"])]
        address = {
            "source_token": {
                "source_gap": source_gap,
                "witness_type": definition["witness_type"],
                "ordered_tagged_endpoint_stable_ids": list(
                    definition["tagged_endpoint_stable_ids"]
                ),
                "endpoint_birth_addresses": source_endpoints,
            },
            "l7_stitch": {
                "l7_parent_gap": child["l7_parent_gap"],
                "step": parent["step"],
                "actual_selected_connector_word": parent[
                    "actual_selected_connector_word"
                ],
                "actual_child_slot_zero_based": child[
                    "actual_parent_connector_step_slot_zero_based"
                ],
                "actual_prefix_vector": child[
                    "l7_parent_connector_prefix_vector"
                ],
            },
            "l8_stitch": {
                "l8_gap": child["l8_gap"],
                "step": child["step"],
                "actual_selected_connector_word": child[
                    "actual_selected_connector_word"
                ],
            },
        }
        state = {
            "schema": "physical-tagged-token-L8-compatibility-state-v1",
            "identity": {
                "source_gap": source_gap,
                "l7_parent_gap": child["l7_parent_gap"],
                "l8_gap": child["l8_gap"],
            },
            "literal_joint_address": address,
            "source_token_owner_profile": joint_source_owner,
            "domain_words": domain_words,
            "local_exact_components": {
                "direct_carried_tagged_pair_site_poison": store.record(
                    direct, domain_words
                ),
                "endpoint_collision": store.record(
                    channel_bits["collision"], domain_words
                ),
                "endpoint_on_candidate_internal_line": store.record(
                    channel_bits["endpoint-old-new-new"], domain_words
                ),
                "endpoint_component_union": store.record(endpoint, domain_words),
                "near_deep_tagged_partner_site_poison": store.record(
                    near, domain_words
                ),
                "full_tagged_token_component": store.record(full, domain_words),
            },
            "endpoint_birth_owner_shell_masks": output_mask_map(
                endpoint_shell_bits, domain_words, store
            ),
            "near_deep_birth_owner_shell_masks": output_mask_map(
                near_shell_bits, domain_words, store
            ),
            "physical_partner_masks": output_mask_map(
                partner_bits, domain_words, store
            ),
            "physical_near_deep_terms": sorted(
                near_terms, key=stable_hash
            ),
            "selected_word_avoids_tagged_component": observation[
                "actual_selected_word_avoids_endpoint_closure"
            ],
            "ordered_l9_successors": [],
        }
        states.append(state)
        raw[identity] = {
            "direct": direct,
            "collision": channel_bits["collision"],
            "endpoint_line": channel_bits["endpoint-old-new-new"],
            "endpoint": endpoint,
            "near": near,
            "full": full,
            "endpoint_shell": dict(endpoint_shell_bits),
            "endpoint_by_id": dict(endpoint_component_bits),
            "near_shell": dict(near_shell_bits),
            "partner": dict(partner_bits),
            "source_owner_shell": joint_source_owner[
                "minimum_joint_owner_base3_shell"
            ],
            "source_endpoint_owner_shells": tuple(sorted(
                (
                    profile["birth_age_at_observation"],
                    profile["minimum_joint_owner_base3_shell"],
                )
                for profile in source_endpoints
            )),
            "address_key": normalize(address),
            "actual_word": tuple(child["actual_selected_connector_word"]),
            "step": child["step"],
            "witness_type": definition["witness_type"],
            "source_ids": definition["tagged_endpoint_stable_ids"],
            "domain_words": domain_words,
        }
    assert len(states) == EXPECTED_TREE["l8"]
    return states, raw


def completed_l8_owner_index():
    with (ROOT / "gate2-l7-construction-L8.pkl").open("rb") as handle:
        state8 = pickle.load(handle)
    gaps = len(state8["words"])
    starts = [0]
    for gap in range(gaps):
        starts.append(starts[-1] + len(state8["words"][gap]))
    assert starts[-1] + 1 == 311_738
    start_to_anchor = {start: index for index, start in enumerate(starts)}

    def owner_options(path_index):
        anchor_index = start_to_anchor.get(path_index)
        if anchor_index is not None:
            options = []
            if anchor_index > 0:
                options.append(anchor_index - 1)
            if anchor_index < gaps:
                options.append(anchor_index)
            assert options
            return tuple(options)
        gap = bisect.bisect_right(starts, path_index) - 1
        assert 0 <= gap < gaps
        assert starts[gap] < path_index < starts[gap + 1]
        return (gap,)

    return owner_options, starts


def build_l9_states(l9, l8_states, l8_raw, store):
    input_payloads = l9["exact_mask_store"]["payloads"]
    endpoint_profiles = {
        profile["stable_id"]: profile
        for profile in l9["anchor_skeleton"]["tagged_endpoint_profiles"]
    }
    partner_profiles = {
        profile["stable_id"]: profile
        for profile in l9["partner_profiles"]["profiles"]
    }
    owner_options_for_path_index, starts = completed_l8_owner_index()
    l8_state_by_id = {
        (
            state["identity"]["source_gap"],
            state["identity"]["l7_parent_gap"],
            state["identity"]["l8_gap"],
        ): state
        for state in l8_states
    }

    states = []
    raw = {}
    grouped_successors = defaultdict(list)
    for record in sorted(
        l9["exact_corridor_masks"]["records"],
        key=lambda item: (
            item["source_gap"], item["l8_gap"],
            item["actual_l8_connector_step_slot_zero_based"],
        ),
    ):
        source_gap = record["source_gap"]
        definition = SOURCE_DEFINITIONS[source_gap]
        assert tuple(record["source_tagged_endpoint_stable_ids"]) == (
            definition["tagged_endpoint_stable_ids"]
        )
        domain_words = record["domain_words"]
        channel_bits = {
            channel: decode_input_mask(
                record["exact_overlapping_channel_masks"][channel],
                input_payloads,
            )
            for channel in CHANNELS_L9
        }
        all_bits = 0
        for bits in channel_bits.values():
            all_bits |= bits
        full_input = decode_input_mask(
            record["exact_tagged_age2_anchor_component_mask"],
            input_payloads,
        )
        assert all_bits == full_input

        atom_bits = {}
        for atom in record["atoms"]:
            atom_bits[atom["atom_id"]] = decode_input_mask(
                atom["exact_witness_union_mask"], input_payloads
            )

        endpoint_component_bits = {
            stable_id: 0 for stable_id in definition[
                "tagged_endpoint_stable_ids"
            ]
        }
        endpoint_all_bits = {
            stable_id: 0 for stable_id in definition[
                "tagged_endpoint_stable_ids"
            ]
        }
        reconstructed_channel_bits = {
            channel: 0 for channel in CHANNELS_L9
        }
        partner_bits = defaultdict(int)
        near_shell_bits = defaultdict(int)
        near_terms = []
        target_tile = record["l8_gap"]
        for atom in record["atoms"]:
            bits = atom_bits[atom["atom_id"]]
            for witness in atom["witnesses"]:
                channel = witness["channel"]
                tagged_id = witness["tagged_endpoint_stable_id"]
                assert tagged_id in endpoint_all_bits
                reconstructed_channel_bits[channel] |= bits
                endpoint_all_bits[tagged_id] |= bits
                if channel in ("collision", "endpoint-old-new-new"):
                    endpoint_component_bits[tagged_id] |= bits
                if channel == "tagged-other-anchor-old-old":
                    partner_id = witness["partner_stable_id"]
                    partner_bits[partner_id] |= bits
                    tagged_profile = endpoint_profiles[tagged_id]
                    partner_profile = partner_profiles[partner_id]
                    assert partner_profile["birth_level"] == witness[
                        "partner_birth_level"
                    ]
                    tagged_owners = owner_options_for_path_index(
                        tagged_profile["l8_path_index_and_l9_anchor_index"]
                    )
                    partner_owners = owner_options_for_path_index(
                        partner_profile[
                            "l8_path_index_and_l9_anchor_index"
                        ]
                    )
                    joint_owner = owner_profile(
                        (tagged_owners, partner_owners), target_tile
                    )
                    shell_key = (
                        tagged_profile["age_at_l9"],
                        partner_profile["age_at_l9"],
                        joint_owner[
                            "minimum_joint_owner_base3_shell"
                        ],
                    )
                    near_shell_bits[shell_key] |= bits
                    near_terms.append({
                        "atom": atom["atom"],
                        "mask": store.record(bits, domain_words),
                        "tagged_endpoint_stable_id": tagged_id,
                        "tagged_birth_level": tagged_profile["birth_level"],
                        "tagged_birth_age": tagged_profile["age_at_l9"],
                        "tagged_owner_options": list(tagged_owners),
                        "partner_stable_id": partner_id,
                        "partner_birth_level": partner_profile["birth_level"],
                        "partner_birth_age": partner_profile["age_at_l9"],
                        "partner_birth_parent_endpoint_stable_ids": (
                            partner_profile[
                                "birth_parent_endpoint_stable_ids"
                            ]
                        ),
                        "partner_owner_options": list(partner_owners),
                        "joint_owner": joint_owner,
                    })

        assert reconstructed_channel_bits == channel_bits
        endpoint_all_input = {
            stable_id: decode_input_mask(mask, input_payloads)
            for stable_id, mask in record[
                "exact_endpoint_masks_overlap"
            ].items()
        }
        assert endpoint_all_bits == endpoint_all_input

        partner_input = {
            stable_id: decode_input_mask(mask, input_payloads)
            for stable_id, mask in record[
                "exact_partner_masks_overlap"
            ].items()
        }
        assert dict(partner_bits) == partner_input
        near = channel_bits["tagged-other-anchor-old-old"]
        shell_union = 0
        for bits in near_shell_bits.values():
            shell_union |= bits
        assert shell_union == near
        direct = channel_bits["tagged-tagged-old-old"]
        endpoint = (
            channel_bits["collision"]
            | channel_bits["endpoint-old-new-new"]
        )
        assert all_bits == direct | endpoint | near

        source_endpoint_owner_profiles = []
        source_owner_options = []
        endpoint_shell_bits = defaultdict(int)
        for stable_id in definition["tagged_endpoint_stable_ids"]:
            profile = endpoint_profiles[stable_id]
            owners = owner_options_for_path_index(
                profile["l8_path_index_and_l9_anchor_index"]
            )
            source_owner_options.append(owners)
            individual_owner = owner_profile((owners,), target_tile)
            item = {
                **profile,
                **individual_owner,
                "birth_age_at_observation": profile["age_at_l9"],
            }
            source_endpoint_owner_profiles.append(item)
            shell_key = (
                profile["age_at_l9"],
                individual_owner[
                    "minimum_joint_owner_base3_shell"
                ],
            )
            endpoint_shell_bits[shell_key] |= endpoint_component_bits[
                stable_id
            ]
        joint_source_owner = owner_profile(
            source_owner_options, target_tile
        )

        l8_id = (source_gap, record["l7_parent_gap"], record["l8_gap"])
        l8_state = l8_state_by_id[l8_id]
        assert record["actual_selected_l8_connector_word"] == (
            l8_state["literal_joint_address"]["l8_stitch"][
                "actual_selected_connector_word"
            ]
        )
        l8_address = l8_state["literal_joint_address"]
        address = {
            **l8_address,
            "source_token": {
                **l8_address["source_token"],
                "endpoint_birth_addresses": source_endpoint_owner_profiles,
            },
            "l9_precursor_stitch": {
                "l9_gap": record["l9_gap"],
                "step": record["step"],
                "actual_parent_l8_word": record[
                    "actual_selected_l8_connector_word"
                ],
                "actual_child_slot_zero_based": record[
                    "actual_l8_connector_step_slot_zero_based"
                ],
                "ordered_corridor_endpoint_stable_ids": record[
                    "ordered_corridor_endpoint_stable_ids"
                ],
                "selected_l9_connector_word": None,
            },
        }
        identity = (
            source_gap, record["l7_parent_gap"], record["l8_gap"],
            record["l9_gap"],
        )
        state = {
            "schema": "physical-tagged-token-L9-precursor-compatibility-state-v1",
            "identity": {
                "source_gap": source_gap,
                "l7_parent_gap": record["l7_parent_gap"],
                "l8_gap": record["l8_gap"],
                "l9_gap": record["l9_gap"],
            },
            "literal_joint_address": address,
            "source_token_owner_profile": joint_source_owner,
            "domain_words": domain_words,
            "local_exact_components": {
                "direct_carried_tagged_pair_site_poison": store.record(
                    direct, domain_words
                ),
                "endpoint_collision": store.record(
                    channel_bits["collision"], domain_words
                ),
                "endpoint_on_candidate_internal_line": store.record(
                    channel_bits["endpoint-old-new-new"], domain_words
                ),
                "endpoint_component_union": store.record(endpoint, domain_words),
                "near_deep_tagged_initial_anchor_site_poison": store.record(
                    near, domain_words
                ),
                "full_tagged_age2_initial_anchor_component": store.record(
                    all_bits, domain_words
                ),
            },
            "endpoint_birth_owner_shell_masks": output_mask_map(
                endpoint_shell_bits, domain_words, store
            ),
            "near_deep_birth_owner_shell_masks": output_mask_map(
                near_shell_bits, domain_words, store
            ),
            "physical_partner_masks": output_mask_map(
                partner_bits, domain_words, store
            ),
            "physical_near_deep_terms": sorted(
                near_terms, key=stable_hash
            ),
            "selected_l9_connector_word": None,
        }
        states.append(state)
        raw[identity] = {
            "direct": direct,
            "collision": channel_bits["collision"],
            "endpoint_line": channel_bits["endpoint-old-new-new"],
            "endpoint": endpoint,
            "near": near,
            "full": all_bits,
            "endpoint_shell": dict(endpoint_shell_bits),
            "endpoint_by_id": dict(endpoint_component_bits),
            "near_shell": dict(near_shell_bits),
            "partner": dict(partner_bits),
            "source_owner_shell": joint_source_owner[
                "minimum_joint_owner_base3_shell"
            ],
            "source_endpoint_owner_shells": tuple(sorted(
                (
                    profile["birth_age_at_observation"],
                    profile["minimum_joint_owner_base3_shell"],
                )
                for profile in source_endpoint_owner_profiles
            )),
            "address_key": normalize(address),
            "step": record["step"],
            "witness_type": definition["witness_type"],
            "source_ids": definition["tagged_endpoint_stable_ids"],
            "domain_words": domain_words,
        }
        successor = {
            "slot": record["actual_l8_connector_step_slot_zero_based"],
            "l9_gap": record["l9_gap"],
            "step": record["step"],
            "ordered_corridor_endpoint_stable_ids": record[
                "ordered_corridor_endpoint_stable_ids"
            ],
        }
        grouped_successors[l8_id].append((successor, identity))

    assert len(states) == EXPECTED_TREE["l9"]
    for l8_id, entries in grouped_successors.items():
        entries.sort(key=lambda item: item[0]["slot"])
        l8_state = l8_state_by_id[l8_id]
        word = l8_state["literal_joint_address"]["l8_stitch"][
            "actual_selected_connector_word"
        ]
        assert [item[0]["slot"] for item in entries] == list(range(len(word)))
        assert [item[0]["step"] for item in entries] == word
        l8_state["ordered_l9_successors"] = [item[0] for item in entries]
        l8_raw[l8_id]["successor_ids"] = tuple(item[1] for item in entries)
    assert len(grouped_successors) == EXPECTED_TREE["l8"]
    return states, raw


def build_l7_states(future, l8_raw, endpoint_origins):
    states = []
    raw = {}
    for parent in sorted(
        future["parent_states"],
        key=lambda record: (record["source_gap"], record["l7_parent_gap"]),
    ):
        source_gap = parent["source_gap"]
        definition = SOURCE_DEFINITIONS[source_gap]
        source_endpoints = []
        for stable_id in definition["tagged_endpoint_stable_ids"]:
            profile = endpoint_origins[stable_id]
            source_endpoints.append({
                "stable_id": stable_id,
                "birth_level": profile["birth_level"],
                "birth_age_at_observation": 0,
                "birth_gap": profile["birth_gap"],
                "interior_ordinal": profile["interior_ordinal"],
                "birth_parent_endpoint_stable_ids": profile[
                    "birth_parent_endpoint_stable_ids"
                ],
            })
        child_ids = tuple(
            (source_gap, parent["l7_parent_gap"], child["l8_gap"])
            for child in parent["ordered_l8_children"]
        )
        for child_id in child_ids:
            assert child_id in l8_raw
        address = {
            "source_token": {
                "source_gap": source_gap,
                "witness_type": definition["witness_type"],
                "ordered_tagged_endpoint_stable_ids": list(
                    definition["tagged_endpoint_stable_ids"]
                ),
                "endpoint_birth_addresses": source_endpoints,
            },
            "l7_stitch": {
                "l7_parent_gap": parent["l7_parent_gap"],
                "step": parent["step"],
                "actual_selected_connector_word": parent[
                    "actual_selected_connector_word"
                ],
            },
        }
        identity = (source_gap, parent["l7_parent_gap"])
        states.append({
            "schema": "physical-tagged-token-L7-parent-transition-state-v1",
            "identity": {
                "source_gap": source_gap,
                "l7_parent_gap": parent["l7_parent_gap"],
            },
            "literal_joint_address": address,
            "source_token_owner_profile": None,
            "source_token_owner_profile_status": (
                "not inferred: the L7 parent trace has no pinned L7 "
                "pipeline completion-tile address; exact birth ancestry is "
                "retained"
            ),
            "ordered_l8_successors": parent["ordered_l8_children"],
        })
        raw[identity] = {
            "step": parent["step"],
            "witness_type": definition["witness_type"],
            "source_ids": definition["tagged_endpoint_stable_ids"],
            "source_birth_ages": tuple(
                profile["birth_age_at_observation"]
                for profile in source_endpoints
            ),
            "address_key": normalize(address),
            "actual_word": tuple(parent["actual_selected_connector_word"]),
            "successor_ids": child_ids,
        }
    assert len(states) == EXPECTED_TREE["l7"]
    return states, raw


def common_local_key(record):
    return (
        record["witness_type"],
        len(record["source_ids"]),
        record["step"],
        record["domain_words"],
        record["direct"],
        record["collision"],
        record["endpoint_line"],
        record["near"],
    )


def local_key(record, variant):
    key = common_local_key(record)
    if variant in ("birth_owner_shell", "physical_partner", "literal_address"):
        key += (
            record["source_owner_shell"],
            record["source_endpoint_owner_shells"],
            mask_key(record["endpoint_shell"]),
            mask_key(record["near_shell"]),
        )
    if variant in ("physical_partner", "literal_address"):
        key += (
            record["source_ids"],
            mask_key(record["endpoint_by_id"]),
            mask_key(record["partner"]),
        )
    if variant == "literal_address":
        key += (record["address_key"],)
    return key


def l7_base_key(record, variant):
    key = (
        record["witness_type"], len(record["source_ids"]), record["step"]
    )
    if variant in ("birth_owner_shell", "physical_partner", "literal_address"):
        key += (record["source_birth_ages"],)
    if variant in ("physical_partner", "literal_address"):
        key += (record["source_ids"],)
    if variant == "literal_address":
        key += (record["address_key"],)
    return key


def assign_colors(nodes, key_function, prefix):
    groups = defaultdict(list)
    for identity in sorted(nodes):
        groups[key_function(nodes[identity])].append(identity)
    ordered = sorted(groups.values(), key=lambda members: members)
    colors = {}
    for index, members in enumerate(ordered):
        color = f"{prefix}{index:04d}"
        for identity in members:
            colors[identity] = color
    histogram = Counter(colors.values())
    return colors, {
        "nodes": len(nodes),
        "classes": len(histogram),
        "singleton_classes": sum(size == 1 for size in histogram.values()),
        "merged_classes": sum(size > 1 for size in histogram.values()),
        "largest_class": max(histogram.values()),
        "class_size_histogram": {
            str(size): count
            for size, count in sorted(Counter(histogram.values()).items())
        },
    }


def transition_audit(nodes, base_key, outcome_key, limit=5):
    grouped = defaultdict(list)
    for identity in sorted(nodes):
        grouped[base_key(nodes[identity])].append(identity)
    noncongruent = []
    repeated = 0
    for members in grouped.values():
        if len(members) < 2:
            continue
        repeated += 1
        outcomes = defaultdict(list)
        for identity in members:
            outcomes[outcome_key(nodes[identity])].append(identity)
        if len(outcomes) > 1:
            noncongruent.append((members, outcomes))
    examples = []
    for members, outcomes in noncongruent[:limit]:
        examples.append({
            "class_members": as_json(members),
            "distinct_ordered_outcomes": [
                {
                    "members": as_json(outcome_members),
                    "outcome": as_json(outcome),
                }
                for outcome, outcome_members in sorted(
                    outcomes.items(), key=lambda item: item[1]
                )
            ],
        })
    return {
        "classes": len(grouped),
        "repeated_classes": repeated,
        "noncongruent_classes": len(noncongruent),
        "maximum_distinct_outcomes": max(
            (len(outcomes) for _members, outcomes in noncongruent),
            default=1,
        ),
        "examples": examples,
        "interpretation": (
            "A noncongruent class is an exact finite falsifier on the one "
            "recorded tree. Zero noncongruent classes is only finite "
            "non-falsification, not a universal congruence proof."
        ),
    }


def partition_refinement(l7_raw, l8_raw, l9_raw):
    variants = (
        "channel",
        "birth_owner_shell",
        "physical_partner",
        "literal_address",
    )
    result = {}
    for variant in variants:
        l9_colors, l9_stats = assign_colors(
            l9_raw, lambda record: local_key(record, variant), "L9C"
        )
        l8_local_colors, l8_local_stats = assign_colors(
            l8_raw, lambda record: local_key(record, variant), "L8B"
        )

        def l8_outcome(record):
            return tuple(
                (
                    slot,
                    l9_raw[successor]["step"],
                    l9_colors[successor],
                )
                for slot, successor in enumerate(record["successor_ids"])
            )

        l8_refined_colors, l8_refined_stats = assign_colors(
            l8_raw,
            lambda record: (
                local_key(record, variant),
                record["actual_word"],
                l8_outcome(record),
            ),
            "L8R",
        )

        def l7_outcome(record):
            return tuple(
                (
                    slot,
                    l8_raw[successor]["step"],
                    l8_refined_colors[successor],
                )
                for slot, successor in enumerate(record["successor_ids"])
            )

        l7_base_colors, l7_base_stats = assign_colors(
            l7_raw, lambda record: l7_base_key(record, variant), "L7B"
        )
        l7_refined_colors, l7_refined_stats = assign_colors(
            l7_raw,
            lambda record: (
                l7_base_key(record, variant),
                record["actual_word"],
                l7_outcome(record),
            ),
            "L7R",
        )
        result[variant] = {
            "round_0_L9_exact_local_partition": l9_stats,
            "round_0_L8_exact_local_partition": l8_local_stats,
            "round_1_L8_ordered_future_refinement": l8_refined_stats,
            "round_1_L7_structural_base_partition": l7_base_stats,
            "round_2_L7_ordered_future_refinement": l7_refined_stats,
            "L8_transition_congruence_audit": transition_audit(
                l8_raw,
                lambda record: (
                    local_key(record, variant), record["actual_word"]
                ),
                l8_outcome,
            ),
            "L7_transition_congruence_audit": transition_audit(
                l7_raw,
                lambda record: (
                    l7_base_key(record, variant), record["actual_word"]
                ),
                l7_outcome,
            ),
            "color_stream_sha256": stable_hash({
                "L9": [
                    [as_json(identity), l9_colors[identity]]
                    for identity in sorted(l9_colors)
                ],
                "L8_local": [
                    [as_json(identity), l8_local_colors[identity]]
                    for identity in sorted(l8_local_colors)
                ],
                "L8_refined": [
                    [as_json(identity), l8_refined_colors[identity]]
                    for identity in sorted(l8_refined_colors)
                ],
                "L7_base": [
                    [as_json(identity), l7_base_colors[identity]]
                    for identity in sorted(l7_base_colors)
                ],
                "L7_refined": [
                    [as_json(identity), l7_refined_colors[identity]]
                    for identity in sorted(l7_refined_colors)
                ],
            }),
        }
    return result


def state_stream_sha256(states):
    return stable_hash(states)


def estimate_result(data, observed, resource_policy):
    requested, _model_sizes, census = requested_atom_inventory(data["deep"])
    l9_records = data["l9"]["exact_corridor_masks"]["records"]
    l9_atoms = sum(len(record["atoms"]) for record in l9_records)
    l9_witnesses = sum(
        len(atom["witnesses"])
        for record in l9_records for atom in record["atoms"]
    )
    return {
        "status": (
            "estimate for exact bounded physical-token compatibility probe; "
            "no masks or partition outcomes computed"
        ),
        "checker_sha256": file_sha256(Path(__file__)),
        "input_sha256": observed,
        "resource_policy": resource_policy,
        "exact_tree": EXPECTED_TREE,
        "planned_L8_raw_mask_rescan": {
            **census,
            "requested_atoms_by_step": {
                str(step): len(atoms)
                for step, atoms in sorted(requested.items())
            },
            "placed_point_pairs_rescanned": 0,
            "semantics": (
                "scan connector words only for the exact atom descriptions "
                "already witnessed by the physical tagged-token audit"
            ),
            "exact_mask_buffer_bytes": sum(
                len(atoms) * ((next(
                    record["domain_words"]
                    for record in data["deep"][
                        "all_domain_endpoint_incidence_closure"
                    ]["model_census"]
                    if record["step"] == step
                ) + 7) // 8)
                for step, atoms in requested.items()
            ),
        },
        "planned_L9_decode": {
            "corridors": len(l9_records),
            "witness_atoms": l9_atoms,
            "witness_records": l9_witnesses,
            "input_exact_payloads": data["l9"]["exact_mask_store"][
                "unique_payloads"
            ],
        },
        "partition_variants": [
            "channel", "birth_owner_shell", "physical_partner",
            "literal_address",
        ],
        "resource_projection": {
            "elapsed_seconds": "60--180",
            "peak_resident_memory_MiB": "300--700",
            "basis": (
                "3,751,509 short connector words versus the pinned L9 "
                "producer's 8,530,195-word model scan; only 2.3 MiB of new "
                "mask buffers, with peak memory dominated by sequential "
                "deserialization of the 74 MiB base and 114 MiB fragile "
                "pickles"
            ),
            "recommended_stop": (
                "stop and inspect if elapsed time exceeds 5 minutes or RSS "
                "exceeds 900 MiB"
            ),
        },
        "scope_warning": (
            "The L9 leaves have no selected connector and omit all current-"
            "L9 prefix interiors. The result can finitely falsify a tested "
            "quotient but cannot certify universal congruence."
        ),
    }


def run_result(data, observed, resource_policy):
    started = time.monotonic()
    store = ExactMaskStore()
    raw_atom_masks, rescan_steps, rescan_census = rescan_l8_atom_masks(
        data["deep"]
    )
    l8_states, l8_raw = build_l8_states(
        data["future"], data["birth"], data["deep"], data["l9"],
        raw_atom_masks, store,
    )
    l9_states, l9_raw = build_l9_states(
        data["l9"], l8_states, l8_raw, store
    )
    endpoint_origins = source_endpoint_origins(data["l9"])
    l7_states, l7_raw = build_l7_states(
        data["future"], l8_raw, endpoint_origins
    )
    partitions = partition_refinement(l7_raw, l8_raw, l9_raw)
    payload_uncompressed = sum(
        payload["uncompressed_bytes"] for payload in store.payloads.values()
    )
    payload_compressed = sum(
        payload["zlib_bytes"] for payload in store.payloads.values()
    )
    effectful = {
        "L8": sum(record["full"] != 0 for record in l8_raw.values()),
        "L9": sum(record["full"] != 0 for record in l9_raw.values()),
    }
    return {
        "status": (
            "exact finite realized-tree physical-token future-compatibility "
            "probe; not a universal Post quotient, availability bound, "
            "contraction lemma, safety certificate, or theorem"
        ),
        "checker_sha256": file_sha256(Path(__file__)),
        "input_sha256": observed,
        "resource_policy": {
            **resource_policy,
            "elapsed_seconds": round(time.monotonic() - started, 3),
        },
        "scope": {
            "physical_source_tokens": len(SOURCE_DEFINITIONS),
            "source_token_definitions": as_json(SOURCE_DEFINITIONS),
            "realized_tree": EXPECTED_TREE,
            "actual_L7_and_L8_connector_choices_retained": True,
            "ordered_parent_slot_addresses_retained": True,
            "independent_endpoint_address_streams": False,
            "alternate_connector_histories": False,
            "L8_prefix_aware_near_deep_join": True,
            "L9_complete_initial_anchor_join": True,
            "L9_selected_connector_word": None,
            "L9_current_prefix_connector_interiors": False,
            "endpoint_or_distance_cutoff": None,
            "all_point_pairs_scanned": False,
        },
        "mask_semantics": {
            "partition_operations": (
                "all equality, OR, and refinement keys use decoded or "
                "reconstructed raw integer bitsets"
            ),
            "hashes": (
                "output commitments only; no mask union, subset, equality, "
                "or transition decision is inferred from hashes"
            ),
            "birth_owner_shell_split": (
                "overlapping exact OR masks keyed by tagged birth age, "
                "partner birth age, and minimum joint owner base-3 shell"
            ),
            "shell_split_is_not_disjoint": True,
        },
        "L8_exact_atom_rescan": {
            **rescan_census,
            "steps": rescan_steps,
            "all_atom_and_channel_commitments_reproduced": True,
            "placed_point_pairs_rescanned": 0,
        },
        "exact_mask_store": {
            "unique_payloads": len(store.payloads),
            "uncompressed_bytes": payload_uncompressed,
            "zlib_bytes": payload_compressed,
            "payloads": store.payloads,
        },
        "states": {
            "L7": l7_states,
            "L8": l8_states,
            "L9": l9_states,
        },
        "compact_summary": {
            "tree_nodes": EXPECTED_TREE,
            "effectful_local_tagged_components": effectful,
            "state_stream_sha256": {
                "L7": state_stream_sha256(l7_states),
                "L8": state_stream_sha256(l8_states),
                "L9": state_stream_sha256(l9_states),
            },
            "partition_refinement": partitions,
            "decisive_interpretation": (
                "Any reported noncongruent repeated class is an exact finite "
                "counterexample to that tested key on this recorded tree. "
                "A zero count is not evidence of all-action closure when "
                "classes are singleton or when L9 actions are absent."
            ),
        },
        "soundness_boundary": {
            "included": [
                "stable physical tagged endpoint identities and their joint birth ancestry",
                "actual selected L7/L8 connector words and exact parent/slot addresses",
                "exact L8 prefix-aware direct, endpoint, and tagged-partner poison",
                "exact L9 direct, endpoint, and tagged-to-every-initial-anchor poison",
                "raw exact birth/owner-shell mask ORs and ordered bottom-up successor refinement",
            ],
            "omitted": [
                "any selected L9 connector word or current-L9 connector prefix",
                "near-deep joins born from a current-L9 connector interior",
                "untagged deep tokens and all-point-pair closure",
                "alternate legal connector histories and all-action Post closure",
                "positive complete availability, contraction, ranking, or infinite safety",
            ],
        },
    }


def atomic_write_json(output, result):
    output = Path(output)
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(
        prefix=output.name + ".", suffix=".tmp", dir=output.parent
    )
    try:
        with os.fdopen(descriptor, "w") as handle:
            json.dump(result, handle, indent=2, sort_keys=True)
            handle.write("\n")
        os.replace(temporary, output)
    except Exception:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("mode", choices=("estimate", "run"))
    parser.add_argument("--future", type=Path, default=DEFAULT_FUTURE)
    parser.add_argument("--birth", type=Path, default=DEFAULT_BIRTH)
    parser.add_argument("--deep", type=Path, default=DEFAULT_DEEP)
    parser.add_argument("--l9", type=Path, default=DEFAULT_L9)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    if args.mode == "run" and args.output is None:
        parser.error("run requires --output")
    resource_policy = enforce_resource_policy()
    data, observed = validate_inputs(args)
    if args.mode == "estimate":
        result = estimate_result(data, observed, resource_policy)
    else:
        result = run_result(data, observed, resource_policy)
    if args.output is None:
        json.dump(result, sys.stdout, indent=2, sort_keys=True)
        sys.stdout.write("\n")
    else:
        atomic_write_json(args.output, result)


if __name__ == "__main__":
    main()
